[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\adchurch\archive\addons\veristand steps for teststand'

[projects.runtime]
path = 'Source\LV\RunTime\VeriStand Steps RunTime Library.lvproj'

[projects.installer]
path = 'Source\LV\Installer\Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvUpdateProjectFiles'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL'
type = 'lvBuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL x64'
type = 'lv64BuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Post Install Action'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'Post Install Action'

[[build.steps]]
name = 'Pre Uninstall Action'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'Pre Uninstall Action'

[[build.steps]]
name = 'TestStand 2014 Installer'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'TestStand 2014 Installer'

[[build.steps]]
name = 'TestStand 2014 Installer'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'TestStand 2016 Installer'

[[build.steps]]
name = 'TestStand 2014 Installer'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'TestStand 2017 Installer'

[package]
type = 'vsStepsPackage'
version = '7.1'
teststand_versions = ['2014','2016','2017']

[[test.steps]]
name = 'Execute Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2014'
