[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\NIVeriStandAdd-ons\archive\addons\veristand steps for teststand'

[projects.runtime]
path = 'Source\LV\RunTime\VeriStand Steps RunTime Library.lvproj'

[projects.installer]
path = 'Source\LV\Installer\Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvUpdateProjectFiles'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL'
type = 'lvBuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL x64'
type = 'lv64BuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'PostInstallAction'
type = 'lvBuildSpec'
project = 'installer'
target = 'My Computer'
build_spec = 'Post Install Action'

[[build.steps]]
name = 'PostInstallAction'
type = 'lvBuildSpec'
project = 'installer'
target = 'My Computer'
build_spec = 'Pre Uninstall Action'

[[build.steps]]
name = 'Installer'
type = 'lvBuildSpec'
project = 'installer'
target = 'My Computer'
build_spec = 'Installer'

[[test.steps]]
name = 'TestStand 2014 Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2014'
include_ts_64 = 'false'

[[test.steps]]
name = 'TestStand 2016 Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2016'
include_ts_64 = 'false'

[[test.steps]]
name = 'TestStand 2017 Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2017'
include_ts_64 = 'false'

[package]
type = 'vsStepsPackage'
types_version = '7.2.2'
teststand_versions = ['2014','2016','2017']
